### ISSUE TITLE
能给一个使用BaseModel的案例吗？

### ISSUE THREAD

**Issue by softmaxs** [idea2app/Taro-Vant-MobX-ts#2]
使用不来

**Comment by TechQuery** [comment]
@softmaxs 我基于我另一个 MobX 开源库写了个更简单的例子：

## 状态管理

https://github.com/idea2app/Taro-Vant-MobX-ts/blob/2e510bc2a96427163812079f4bcd5c58eec85b62/src/store/Repository.ts#L1-L18

## 页面组件
 
https://github.com/idea2app/Taro-Vant-MobX-ts/blob/2e510bc2a96427163812079f4bcd5c58eec85b62/src/pages/interface.tsx#L1-L41
